### ISSUE TITLE
Will you be able to add a battery icon?

### ISSUE THREAD

**Issue by nichroot** [Hashino/dotfiles#3]
Hey,  First of all thanks for the amazing rice 😻🙏! Its honestly the best setup I've seen in a while and actually the only one that kind of suits my vibe. I'm using it on a laptop, but I can't seem to find the battery icon on the bar. Is it a message problem or does the setup actually not have a battery icon?

**Comment by Hashino** [comment]
I just use [cbatticon](https://github.com/valr/cbatticon) on my notebook. Tried to make a custom widget with awesome but seemed more trouble than it was worth when cbatticon does everything I need. Just install it and add `run cbatticon` to .config/awesome/autorun.sh

And thanks for the compliment. I couldn't find dotfiles that were polished and consistent and also minimalist. Then I saw [b4skyx's](https://github.com/b4skyx/dotfiles) dots and got inspired to make my own.

**Comment by Hashino** [comment]
latest commit should fix this. update and restart awesome.

manual install of `cbatticon` is required

**Comment by nichroot** [comment]
thanks a lot man! Is there any other tweaks you have on your laptop apart from the stuff from your script?

**Comment by Hashino** [comment]
Honestly don't remember. My notebook broke and I've been to lazy to buy a new one. As far as I can recall this was it. Only thing I'd change is the time to lock screen and change doas config to persist instead of nopass. Honestly I just set it as nopass in the install script to not have to enter my password again while it is running.

**Comment by nichroot** [comment]
Alright so I just installed the setup again rn but I don't think there's the new animations are enabled, it's just like the old one. Also how do I enable tap to click. (I know I shouldn't be asking these here, but please excuse me and I'm really sorry 🥹🙏)

**Comment by Hashino** [comment]
You have to install `picom-git` for the animations. And I have no idea on how to configure awesome for touch. 

It seems you'll have to do some device config to make your touch inputs to behave like mouse clicks. https://wiki.archlinux.org/title/Touchscreen

**Comment by Hashino** [comment]
eventually the animations will to the main release of picom so I don't want to change my install script to install the git version. It seems the kind of thing that'll forgot and an year from now would be pulling my hair because picom isn't working like I expected

**Comment by Hashino** [comment]
keep in mind that the animations are in active development. there's constantly new features being implemented and I'm experimenting with them. so don't be shocked if the animations change and/or start working differently in the next commits. now that I know that someone else also use my dots I may make a `stable` branch. I very much use the main branch as my dev branch (specially now that uni is in recess and I have free time to play around)

**Comment by nichroot** [comment]
I don't want stable, I want to be in the dev branch with you lol 🙂‍↔️😭

**Comment by nichroot** [comment]
also hey would be nice if you could help me with some basic keybindings of the system or like keybinding for a cheatsheet maybe? I think you could put in like a small cheatsheet in the readme too

**Comment by Hashino** [comment]
pressing super+s shows the keybindings. If you want to look further into what which keybind does look inside `.config/awesome/hash/keybindings.lua`
inside neovim use `Telescope keymaps` to see keymaps
the descriptions of the keybindings need some work. feel free to make pull requests to improve

**Comment by Hashino** [comment]
send me an email, so we can chat via discord: [iam.ravara@gmail.com](mailto:iam.ravara@gmail.com)

**Comment by nichroot** [comment]
> send me an email, so we can chat via discord: [iam.ravara@gmail.com](mailto:iam.ravara@gmail.com)

Alright!
